# Generated by Django 6.0.6 on 2026-07-17 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tradeoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoffProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handoff_at', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', '同意待ち'), ('accepted', '確定'), ('withdrawn', '取り下げ'), ('cancelled', 'キャンセル')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_proposals', to='main.tradeoffer')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('trade_offer',), name='one_accepted_handoff_per_trade_offer')],
            },
        ),
    ]
