# Generated by Django 6.0.6 on 2026-07-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_userprofile_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoffproposal',
            name='buyer_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handoffproposal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handoffproposal',
            name='seller_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
