# Generated by Django 6.0.6 on 2026-07-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_handoffproposal_buyer_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoffproposal',
            name='status',
            field=models.CharField(choices=[('pending', '同意待ち'), ('accepted', '確定'), ('rejected', '同意されず'), ('withdrawn', '取り下げ'), ('cancelled', 'キャンセル')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='status',
            field=models.CharField(choices=[('pending', '同意待ち'), ('accepted', '成立'), ('rejected', '同意されず'), ('withdrawn', '取り下げ'), ('cancelled', 'キャンセル')], default='pending', max_length=20),
        ),
    ]
