# Generated by Django 6.0.6 on 2026-07-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_handoffproposal_status_alter_tradeoffer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', '出品中'), ('in_progress', '取引中'), ('sold', '売却済み'), ('withdrawn', '取り下げ済み')], default='available', max_length=20),
        ),
    ]
