from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path("search/", views.search, name="search"),
    path("user/<int:user_id>/", views.user_profile, name="user_profile"),
    path("listing/new/", views.listing_form, name="listing_form"),
    path("book/<int:book_id>/", views.book_detail, name="book_detail"),
    path("book/<int:book_id>/like/", views.toggle_like, name="toggle_like"),
    path("book/<int:book_id>/consult/", views.start_consultation, name="start_consultation"),
    path("book/<int:book_id>/chat/", views.chat, name="chat"),
    path("book/<int:book_id>/offer/", views.create_trade_offer, name="create_trade_offer"),
    path("trade-offer/<int:offer_id>/accept/", views.accept_trade_offer, name="accept_trade_offer"),
    path("trade-offer/<int:offer_id>/reject/", views.reject_trade_offer, name="reject_trade_offer"),
    path("trade-offer/<int:offer_id>/handoff/", views.create_handoff_proposal, name="create_handoff_proposal"),
    path("handoff/<int:proposal_id>/accept/", views.accept_handoff_proposal, name="accept_handoff_proposal"),
    path("handoff/<int:proposal_id>/reject/", views.reject_handoff_proposal, name="reject_handoff_proposal"),
    path("handoff/<int:proposal_id>/complete/", views.confirm_handoff_complete, name="confirm_handoff_complete"),
    path("book/<int:book_id>/evaluate/", views.evaluate_trade, name="evaluate_trade"),
    path("book/<int:book_id>/cancel/", views.cancel_trade, name="cancel_trade"),
    path("book/<int:book_id>/edit/", views.edit_book, name="edit_book"),
    path("book/<int:book_id>/withdraw/", views.withdraw_book, name="withdraw_book"),
    path("inbox/", views.inbox, name="inbox"),
    path("mypage/", views.mypage, name="mypage"),
    path("mypage/edit/", views.edit_profile, name="edit_profile"),
    path("help/", views.help_contact, name="help_contact"),
    path("terms/", views.terms, name="terms"),
    path("privacy/", views.privacy_policy, name="privacy_policy"),
]
